---

- hosts: all
  become: true
  become_method: sudo

  vars:
    mmonit_setup_url: http://127.0.0.1:2811
    mmonit_workspace: '/opt'

    mmonit_server_ip: "{{ ansible_default_ipv4.address }}"
    mmonit_server_hostname: "{{ ansible_hostname }}"

  tasks:
    - name: Display IPv4 Address
      debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']

  roles:
    - role: '{{playbook_dir}}'