---

- hosts: all
  become: true
  become_method: sudo

  vars:
    mmonit_setup_url: http://127.0.0.1:2811
    mmonit_collector: "{{ mmonit_connectors.0.scheme | default('http') }}://{{ mmonit_connectors.0.username }}:{{ mmonit_connectors.0.password }}@{{ mmonit_server_ip }}:{{ mmonit_connectors.0.port }}/collector"

  roles:
    - role: '{{playbook_dir}}'