---

- hosts: all
  become: true
  become_method: sudo

  vars:
    mmonit_setup_url: http://127.0.0.1:2811
    mmonit_workspace: '/opt'
    mmonit_connectors:
      - name: 'Default'
        address: '*'
        port: 2811
        processors: 10
        scheme: http
        username: 'admin'
        password: 'monit'
    mmonit_collector: "{{ mmonit_connectors.0.scheme | default('http') }}://{{ mmonit_connectors.0.username }}:{{ mmonit_connectors.0.password }}@{{ mmonit_server_ip }}:{{ mmonit_connectors.0.port }}/collector"

    mmonit_server_ip: '192.168.64.52'
    mmonit_server_hostname: 'mmonit'

  tasks:
    - name: Display IPv4 Address
      debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']

  roles:
    - role: '{{playbook_dir}}'