---

- name: Ensure ssl save paths exist
  no_log: true
  file:
    path: '{{ mmonit_ssl_path }}'
    state: directory
    owner: root
    group: root
    mode: '0440'
  when: mmonit_ssl_path is defined

- name: Read SSL Certificate
  command: cat {{ mmonit_ssl_certificate_path }}
  register: mmonit_ssl_certificate
  changed_when: false

- name: Read SSL Key
  command: cat {{ mmonit_ssl_certificate_key_path }}
  register: mmonit_ssl_certificate_key
  changed_when: false
  
- name: Generate certificate.pem
  no_log: true
  notify: restart mmonit
  template:
    src: 'ssl/certificate.pem'
    dest: '{{ mmonit_ssl_path }}/certificate.pem'
    owner: root
    group: root
    mode: 0700
  when: mmonit_ssl_certificate != '' and mmonit_ssl_certificate_key != ''
