---

- name: Ensure ssl save paths exist
  no_log: true
  file:
    path: '{{ mmonit_ssl_path }}'
    state: directory
    owner: root
    group: root
    mode: '0440'
  when: mmonit_ssl_path is defined

- name: Generate dhparam.pem if it does not exist
  openssl_dhparam:
    path: '{{ mmonit_ssl_path }}/dhparam.pem'
    size: '{{ mmonit_dhparam_size }}'

- name: Read dhparam
  command: cat {{ mmonit_ssl_path }}/dhparam.pem
  register: mmonit_ssl_dhparam
  changed_when: false

- name: Generate monit.pem
  no_log: true
  notify: restart mmonit
  template:
    src: 'ssl/certificate.pem'
    dest: '{{ mmonit_ssl_path }}/certificate.pem'
    owner: root
    group: root
    mode: 0700
  when: mmonit_ssl_certificate != '' and mmonit_ssl_certificate_key != ''
