---
- name: start mmonit
  service:
    name: 'monit'
    state: started
    enabled: yes

- name: restart mmonit
  service:
    name: 'mmonit'
    state: restarted
    enabled: yes

- name: reload systemd
  command: systemctl daemon-reload

- name: reload initctl
  command: initctl reload-configuration
