---
- name: start mmonit
  service:
    name: 'monit'
    state: started
    enabled: yes

- name: restart mmonit
  service:
    name: 'mmonit'
    state: restarted
    enabled: yes

- name: reload systemd
  systemd:
    daemon_reload: yes
